### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by Cardistymo** [jobfeikens/rcon#2]
When I call rcon.authenticate("password");
i get an java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;

**Comment by Cardistymo** [comment]
Here are more specific information:

at nl.vv32.rcon.PacketWriter.write(PacketWriter.java:27)
at nl.vv32.rcon.Rcon.writeAndRead(Rcon.java:61)
at nl.vv32.rcon.Rcon.authenticate(Rcon.java:35)

**Comment by Cardistymo** [comment]
I think this should help:
https://stackoverflow.com/questions/48693695/java-nio-buffer-not-loading-clear-method-on-runtime

**Comment by Cardistymo** [comment]
change line 27 in PacketWriter from
`buffer.clear()`
to
`((Buffer) buffer).clear`

**Comment by jobfeikens** [comment]
I'll compile the .jar with java 8 soon which should fix the issue. A temporary fix would be to use java 9 or higher

**Comment by Cardistymo** [comment]
ok thx ill close the issue
