### ISSUE TITLE
Multiple icon servers connection issue

### ISSUE THREAD

**Issue by shkipan** [jobfeikens/rcon#4]
Greetings!

I have a machine with several (currently two) Minecraft servers running on it and a Spring Java application, which is supposed to send commands to these servers through rcon. 

Here's an example of RconServer class, which hold data, required for rcon connection:
```
public class RconServer {
	private Integer id;
	private String url;
	private Integer port;
	private String password;
}
```
Also, I've implemented a command handler using your example from README:
```
               RconServer server = rconConfig.getServers().stream()
			.filter(s -> s.getId().equals(serverId))
			.findFirst()
			.orElseThrow(() -> new RestResourceNotFoundException("Server", "id", String.valueOf(serverId)));

		try(Rcon rcon = Rcon.open(server.getUrl(), server.getPort())) {
			if (rcon.authenticate(server.getPassword())) {
				String response = rcon.sendCommand(command);
				rcon.close();
				return response;
			} else {
				System.out.println("Failed to authenticate");
				return "fail";
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
```

And everything works great if only one server is running. But when I launch two servers, sometimes I get a "Connection refused" exception for one server. And if both servers are reachable, sometimes I get a "Connection reset" exception while sending commands for both servers in turn (not simultaneously). Both servers are configured for running at different ports, so no conflicts here.

Currently I'm not able to reproduce "Connection refused" error, but it happens on this code string
`		try(Rcon rcon = Rcon.open(server.getUrl(), server.getPort())) {
`

Here's stacktrace for "Connection reset" case:

> java.net.SocketException: Connection reset
> 	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:367)
> 	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:398)
> 	at nl.vv32.rcon.PacketReader.readUntilAvailable(PacketReader.java:41)
> 	at nl.vv32.rcon.PacketReader.read(PacketReader.java:22)
> 	at nl.vv32.rcon.Rcon.read(Rcon.java:74)
> 	at nl.vv32.rcon.Rcon.writeAndRead(Rcon.java:67)
> 	at nl.vv32.rcon.Rcon.authenticate(Rcon.java:35)
> 	at com.example.omhms.service.rcon.RconServiceDefault.sendCommand(RconServiceDefault.java:24)
> 	at com.example.omhms.controller.RconController.sendCommand(RconController.java:51)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
> 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
> 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
> 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
> 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
> 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
> 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
> 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.base/java.lang.Thread.run(Thread.java:832)
> 

Could you help me find out, what's happening here and how to fix these issues? Is it happening because my Minecraft servers
are not configured correctly, or because something is wrong with the Java machine? Would be great to work with your cool lib without exceptions)

**Comment by jobfeikens** [comment]
Hi! I don't see anything wrong with the code you provided. You dont have to call rcon.close() since the try block does that for you automatically but that shouldnt matter. Are you running the rcon servers on different ports (rcon.port in server.properties)?

**Comment by shkipan** [comment]
I've called rcon.close(), because thought, that it could help)

Yes, my servers have different ports for rcon and server itself. Here are screenshots of both configs

![Снимок экрана 2021-12-27 в 14 14 18](https://user-images.githubusercontent.com/33808396/147470912-a7e77b4a-c6d1-419e-a54e-f203efbfb0a7.png)
![Снимок экрана 2021-12-27 в 14 14 05](https://user-images.githubusercontent.com/33808396/147470915-43fb4511-b79a-4720-9164-dbee7778e852.png)

**Comment by jobfeikens** [comment]
I wasn't able to reproduce the issue using the following code
```
    static int[] ports = {25575, 25576};

    public static void main(String... args) throws IOException {
        for (int i = 0; i < 1000; i++) {
            try (Rcon rcon = Rcon.open("localhost", ports[i%2])) {
                if (!rcon.authenticate("password")) {
                    throw new IOException("WRONG PASS");
                }
                System.out.println(rcon.sendCommand("list"));
            }
        }
    }
```
![2021-12-27_14-15](https://user-images.githubusercontent.com/25356841/147475519-7c5a515a-304b-4c46-b214-9bbdbfd3f983.png)

Can you confirm this code works in your setup?

**Comment by shkipan** [comment]
Pretty strange, I've launched it several times, sometimes it works, sometimes it get same error

> java.net.SocketException: Connection reset
> 	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:367)
> 	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:398)
> 	at nl.vv32.rcon.PacketReader.readUntilAvailable(PacketReader.java:41)
> 	at nl.vv32.rcon.PacketReader.read(PacketReader.java:22)
> 	at nl.vv32.rcon.Rcon.read(Rcon.java:74)
> 	at nl.vv32.rcon.Rcon.writeAndRead(Rcon.java:67)
> 	at nl.vv32.rcon.Rcon.authenticate(Rcon.java:35)
> 	at com.example.omhms.service.rcon.RconServiceDefault.sendCommand(RconServiceDefault.java:36)
> 	at com.example.omhms.controller.RconController.sendCommand(RconController.java:51)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
> 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
> 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
> 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
> 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
> 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
> 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
> 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.base/java.lang.Thread.run(Thread.java:832)
> There are 0/20 players online:
> There are 0/20 players online:
> There are 0/20 players online:
> There are 0/20 players online:
> There are 0/20 players online:
> There are 0/20 players online:
> There are 0/20 players online:
> There are 0/20 players online:
>
