### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by shkipan** [jobfeikens/rcon#5]
Unicode characters are ignored and transferred into question marks. Seems like something is wrong with request encoding. Could you please update the code to work with Unicode characters?

**Comment by jobfeikens** [comment]
According to [https://developer.valvesoftware.com/wiki/Source_RCON_Protocol](url), strings should be encoded as ASCII. But adding a feature to change the packet codec is fine by me.

**Comment by jobfeikens** [comment]
Added in 1.2.0

**Comment by shkipan** [comment]
Thank you very much for such operative reaction!
